- name: Ensure mysql-server is installed latest version
  apt: name=mysql-server state=latest
  tags: installation

- name: Installing python module MySQL-python
  pip:
    name: MySQL-python
  tags: setup

- name: Ensure mysql-server is running
  service:
    name: mysql
    state: started
